### ISSUE TITLE
Sketch Update 50.2 - Loading of artboards takes "hours"

### ISSUE THREAD

**Issue by l-i-n-k** [Frontify/sketch#1]
Some changes in Sketch 50.2 seem to break the fast loading of artboards in the Frontify PlugIn. After minutes of loading, it says "No artboards found"

**Comment by brunschgi** [comment]
Hi Thommy
Does this issue still exist at your side? 
Best, Remo

**Comment by brunschgi** [comment]
Hi Thommy
Thanks for the videos. We have just analysed the API calls for your scenario and somehow the SHA1  calculation for some of the files are not working correctly. We'll keep you up to date about our findings.

**Comment by brunschgi** [comment]
Hi Thommy
Just deployed the fix to your Frontify instance. The artboards are loading now instant again ;-)
